const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const JobDescSchema = Schema({
  organizationunit:{
    type:String,
    required:true
  },
  reportsto:{
    type:String,
    required:true
  },
  jobholder:{
    type:String,
    required:true
  },
  noOfDirectReports:{
    type:String,
    required:true
  },
  totalStaffCon:{
    type:String,
    required:true
  },
  jobPurpose:{
    type:String,
    required:true
  },
  unitCon:{
    type:String,
    required:true
  },
  keyResultArea:{
    type:String,
    required:true
  },
  avarage:{
    type:String,
    required:true
  },
  keyPerformanceArea:{
    type:String,
    required:true
  },
  keyPerformanceIndicator:{
    type:String,
    required:true
  },
  knowledge:{
    type:String,
    required:true
  },
  specialSkill:{
    type:String,
    required:true
  },
  personalQualities:{
    type:String,
    required:true
  },
  mainTaskRes:{
    type:String,
    required:true
  },
  expectedPerformanceStd:{
    type:String,
    required:true
  },
  additionalComments:{
    type:String,
    required:true
  },
  authorname:{
    type:String,
    required:true
  },
  authorSignature:{
    type:String,
    required:true
  },
  date:{
    type:Date,
    default:Date.now()
  },
  hAuthorName:{
    type:String,
    required:true
  },
  hAuthorSignature:{
    type:String,
    required:true
  },
  hdate:{
    type:Date,
    defualt:Date.now()
  },
  jAuthorName:{
    type:String,
    required:true
  },
  jAuthorSignature:{
    type:String,
    required:true
  },
  jdate:{
    type:Date,
    defualt:Date.now()
  }
});

module.exports = JobDescSchema = mongoose.model("job-desc",JobDescSchema);